### ISSUE TITLE
ENV vars are not available in the hooks scripts

### ISSUE THREAD

**Issue by ianneub** [tutumcloud/builder#33]
It seems that the ENV variables specified in the readme that should exist while the hooks are running are not actually there.

`docker run --rm -it --privileged -v $(pwd):/app -v $HOME/.dockercfg:/.dockercfg:ro --volumes-from builder_cache tutum/builder:staging asdf`

Here is my `hooks/push` file:
```sh
#!/bin/sh

env
gh-release create fenderton/sqs_worker "$IMAGE_NAME"
```
And the output:
```
=> Executing hooks/push hook
HOSTNAME=0cc98cd00027
SHLVL=1
HOME=/root
OLDPWD=/
_=./hooks/push
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/src
```

I would expect the `IMAGE_NAME` env var to be available and be set to `asdf`.

**Comment by pchico83** [comment]
You need to provide the variables to the `tutum/builder` container. What Tutum does is to configure a webhook in github in order to deploy a `tutum/builder` container with the right ENV variables. Therefore, the ENV variables would be available when building from Tutum, but you have to provide them if you want to use the `tutum/builder` image in your own.

**Comment by ianneub** [comment]
Thanks @pchico83 !
